Repository JISUtudy/Weather_iPhone, pull requests merged in 2022-05, with the labels that each got.

#2 [Style] 메인 화면 배경 및 타이틀 설정
  Weather_iPhone.xcworkspace/xcuserdata/jiseok.xcuserdatad/UserInterfaceState.xcuserstate
  Weather_iPhone/Applications/AppDelegate.swift
  Weather_iPhone/Sources/ViewController.swift
Labels: 🙋🏻‍♂️ 지석, 🎨 [Style]

#4 [Fix] UINavigation Bar Large TitleColor (#3)
  Weather_iPhone.xcworkspace/xcuserdata/jiseok.xcuserdatad/UserInterfaceState.xcuserstate
  Weather_iPhone/Applications/AppDelegate.swift
  Weather_iPhone/Sources/ViewController.swift
Labels: 📌 [Fix], 🙋🏻‍♂️ 지석

#7 [Style] Navgation Bar button (#5)
  Weather_iPhone.xcworkspace/xcuserdata/jiseok.xcuserdatad/UserInterfaceState.xcuserstate
  Weather_iPhone/Applications/Base.lproj/LaunchScreen.storyboard
  Weather_iPhone/Sources/ViewController.swift
Labels: 🙋🏻‍♀️ 수정, 🙋🏻‍♂️ 지석, 🎨 [Style]

#11 [Style] SearchBar UI 작업 (#10)
  Weather_iPhone.xcworkspace/xcuserdata/jiseok.xcuserdatad/UserInterfaceState.xcuserstate
  Weather_iPhone/Sources/ViewController.swift
Labels: 🙋🏻‍♀️ 수정, 🙋🏻‍♂️ 지석, 🎨 [Style]

#13 [Style] UITalbeView UI 작업
  Weather_iPhone.xcodeproj/project.pbxproj
  Weather_iPhone.xcworkspace/xcuserdata/jiseok.xcuserdatad/UserInterfaceState.xcuserstate
  Weather_iPhone/Applications/SceneDelegate.swift
  Weather_iPhone/Sources/Controller/MainViewController.swift
Labels: 🙋🏻‍♀️ 수정, 🙋🏻‍♂️ 지석, 🎨 [Style]

#14 [Style] TableView Weather Cell (#8)
  Weather_iPhone.xcodeproj/project.pbxproj
  Weather_iPhone/Sources/Controller/MainViewController.swift
  Weather_iPhone/Sources/Utils/UILabel+Extensions.swift
  Weather_iPhone/Sources/WeatherTableViewCell.swift
Labels: 🙋🏻‍♀️ 수정, 🎨 [Style]
